name: Build Docker Container & Push to DO Registry

on:
  workflow_call:
  workflow_dispatch:
    
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_django:
    uses: Althaf-official/django-k8s-1.0/.github/workflows/test-django.yaml@main
  docker-build:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: test-key-not-good-maybe-one-better
    steps:
    - uses: actions/checkout@v3

        